In [1]:
import numpy as np
import torch
import pandas as pd
import time

In [2]:
def dataloader(path):
    df = pd.read_csv(path)
    data = df.iloc[:, 1:].values
    data = torch.tensor(data).T
    return data
    
emg_file = 'emg-decomp-fastica-edwin/Data/ramp_10mu_20s/emg_data.csv'
df = pd.read_csv(emg_file)

In [3]:
df

Unnamed: 0         0         1         2         3         4         5  \
0               0 -0.025664 -0.025335 -0.017371 -0.005902  0.005362  0.013653   
1               1 -0.057932 -0.057327 -0.038994 -0.013001  0.012443  0.030714   
2               2 -0.086614 -0.086414 -0.059667 -0.022196  0.014226  0.039255   
3               3 -0.110915 -0.111730 -0.078714 -0.033109  0.010818  0.039267   
4               4 -0.130264 -0.132601 -0.095637 -0.045617  0.001969  0.030264   
...           ...       ...       ...       ...       ...       ...       ...   
39995       39995  0.283034  0.437134  0.608423  0.676935  0.739443  0.779771   
39996       39996  0.258109  0.430644  0.622738  0.682550  0.736212  0.766975   
39997       39997  0.218398  0.406571  0.619959  0.675908  0.725813  0.751687   
39998       39998  0.153103  0.354033  0.591858  0.652711  0.707719  0.736046   
39999       39999  0.070461  0.281122  0.545088  0.617284  0.683877  0.719768   

              6         7         8  ...        54        55        56  \
0      0.024019  0.033033 -0.039242  ... -0.144276 -0.177739 -0.018460   
1      0.053957  0.073983 -0.089092  ... -0.333899 -0.410472 -0.041882   
2      0.073028  0.102673 -0.132430  ... -0.508758 -0.624178 -0.063090   
3      0.080823  0.118177 -0.168120  ... -0.662671 -0.811113 -0.081638   
4      0.076382  0.118977 -0.195446  ... -0.792330 -0.967108 -0.097315   
...         ...       ...       ...  ...       ...       ...       ...   
39995  0.766606  0.677128 -0.025373  ... -0.363085 -0.454237 -0.274294   
39996  0.745749  0.646615 -0.100062  ... -0.464645 -0.522417 -0.304247   
39997  0.726870  0.621740 -0.183709  ... -0.563589 -0.602556 -0.344737   
39998  0.716308  0.613242 -0.290873  ... -0.708321 -0.752482 -0.400442   
39999  0.710381  0.613235 -0.411121  ... -0.877747 -0.946381 -0.463043   

             57        58        59        60        61        62        63  
0     -0.021754 -0.026438 -0.033328 -0.040176 -0.046966 -0.066695 -0.090421  
1     -0.049532 -0.060425 -0.076470 -0.092414 -0.108219 -0.153190 -0.207045  
2     -0.075057 -0.092507 -0.118634 -0.144608 -0.170359 -0.238760 -0.319967  
3     -0.097720 -0.121712 -0.158186 -0.194459 -0.230428 -0.319408 -0.424043  
4     -0.117172 -0.147467 -0.194181 -0.240652 -0.286745 -0.392820 -0.516252  
...         ...       ...       ...       ...       ...       ...       ...  
39995 -0.238718 -0.181642 -0.092089 -0.001552  0.089834  0.008706 -0.132343  
39996 -0.287262 -0.245105 -0.165494 -0.084650 -0.002811 -0.078597 -0.207672  
39997 -0.346865 -0.318149 -0.243861 -0.168128 -0.091303 -0.164470 -0.287356  
39998 -0.423481 -0.408668 -0.338083 -0.265853 -0.192447 -0.271916 -0.401437  
39999 -0.506354 -0.504442 -0.435918 -0.365578 -0.293987 -0.386184 -0.531731  

[40000 rows x 65 columns]

In [4]:
df.iloc[:, 1:]

0         1         2         3         4         5         6  \
0     -0.025664 -0.025335 -0.017371 -0.005902  0.005362  0.013653  0.024019   
1     -0.057932 -0.057327 -0.038994 -0.013001  0.012443  0.030714  0.053957   
2     -0.086614 -0.086414 -0.059667 -0.022196  0.014226  0.039255  0.073028   
3     -0.110915 -0.111730 -0.078714 -0.033109  0.010818  0.039267  0.080823   
4     -0.130264 -0.132601 -0.095637 -0.045617  0.001969  0.030264  0.076382   
...         ...       ...       ...       ...       ...       ...       ...   
39995  0.283034  0.437134  0.608423  0.676935  0.739443  0.779771  0.766606   
39996  0.258109  0.430644  0.622738  0.682550  0.736212  0.766975  0.745749   
39997  0.218398  0.406571  0.619959  0.675908  0.725813  0.751687  0.726870   
39998  0.153103  0.354033  0.591858  0.652711  0.707719  0.736046  0.716308   
39999  0.070461  0.281122  0.545088  0.617284  0.683877  0.719768  0.710381   

              7         8         9  ...        54        55        56  \
0      0.033033 -0.039242 -0.044887  ... -0.144276 -0.177739 -0.018460   
1      0.073983 -0.089092 -0.102233  ... -0.333899 -0.410472 -0.041882   
2      0.102673 -0.132430 -0.152433  ... -0.508758 -0.624178 -0.063090   
3      0.118177 -0.168120 -0.194138  ... -0.662671 -0.811113 -0.081638   
4      0.118977 -0.195446 -0.226412  ... -0.792330 -0.967108 -0.097315   
...         ...       ...       ...  ...       ...       ...       ...   
39995  0.677128 -0.025373  0.198529  ... -0.363085 -0.454237 -0.274294   
39996  0.646615 -0.100062  0.152654  ... -0.464645 -0.522417 -0.304247   
39997  0.621740 -0.183709  0.083223  ... -0.563589 -0.602556 -0.344737   
39998  0.613242 -0.290873 -0.026649  ... -0.708321 -0.752482 -0.400442   
39999  0.613235 -0.411121 -0.164330  ... -0.877747 -0.946381 -0.463043   

             57        58        59        60        61        62        63  
0     -0.021754 -0.026438 -0.033328 -0.040176 -0.046966 -0.066695 -0.090421  
1     -0.049532 -0.060425 -0.076470 -0.092414 -0.108219 -0.153190 -0.207045  
2     -0.075057 -0.092507 -0.118634 -0.144608 -0.170359 -0.238760 -0.319967  
3     -0.097720 -0.121712 -0.158186 -0.194459 -0.230428 -0.319408 -0.424043  
4     -0.117172 -0.147467 -0.194181 -0.240652 -0.286745 -0.392820 -0.516252  
...         ...       ...       ...       ...       ...       ...       ...  
39995 -0.238718 -0.181642 -0.092089 -0.001552  0.089834  0.008706 -0.132343  
39996 -0.287262 -0.245105 -0.165494 -0.084650 -0.002811 -0.078597 -0.207672  
39997 -0.346865 -0.318149 -0.243861 -0.168128 -0.091303 -0.164470 -0.287356  
39998 -0.423481 -0.408668 -0.338083 -0.265853 -0.192447 -0.271916 -0.401437  
39999 -0.506354 -0.504442 -0.435918 -0.365578 -0.293987 -0.386184 -0.531731  

[40000 rows x 64 columns]

In [3]:
X = dataloader(emg_file)

In [244]:
X = torch.tensor([[1.,2.,3.,4.,5.],[11.,12.,13.,14.,15.]]) 

In [4]:
D = X - torch.mean(X, -1, True)
D

tensor([[-0.0396, -0.0718, -0.1005,  ...,  0.2045,  0.1392,  0.0566],
        [-0.0385, -0.0705, -0.0996,  ...,  0.3934,  0.3408,  0.2679],
        [-0.0297, -0.0513, -0.0720,  ...,  0.6076,  0.5795,  0.5328],
        ...,
        [-0.0460, -0.1073, -0.1694,  ..., -0.0903, -0.1915, -0.2930],
        [-0.0682, -0.1547, -0.2403,  ..., -0.1660, -0.2734, -0.3877],
        [-0.0965, -0.2131, -0.3260,  ..., -0.2934, -0.4075, -0.5378]],
       dtype=torch.float64)

In [5]:
cov = torch.cov(D,correction=0)
cov

tensor([[1.3812, 1.4008, 1.3055,  ..., 0.3811, 0.3924, 0.4066],
        [1.4008, 1.4733, 1.4337,  ..., 0.3140, 0.3293, 0.3408],
        [1.3055, 1.4337, 1.4954,  ..., 0.1973, 0.2117, 0.2133],
        ...,
        [0.3811, 0.3140, 0.1973,  ..., 1.8609, 1.7919, 1.6707],
        [0.3924, 0.3293, 0.2117,  ..., 1.7919, 1.7532, 1.6681],
        [0.4066, 0.3408, 0.2133,  ..., 1.6707, 1.6681, 1.6351]],
       dtype=torch.float64)

In [16]:
L, V = torch.linalg.eig(cov)

In [11]:
L, V = torch.linalg.eigh(cov,'L')

In [17]:
L, V = L.real, V.real

In [238]:
# L, V = torch.round(L.real, decimals=4) , torch.round(V.real, decimals=4)

In [12]:
V

tensor([[-4.8032e-04,  7.4991e-04, -5.6222e-02,  ...,  8.0374e-02,
          2.2313e-01, -3.6751e-02],
        [ 1.1279e-03, -1.7613e-03,  1.3199e-01,  ...,  8.4061e-02,
          2.3968e-01, -2.7614e-02],
        [ 3.4412e-02, -2.1535e-01, -3.3970e-02,  ...,  9.9830e-02,
          2.3573e-01, -1.0243e-02],
        ...,
        [ 5.5293e-04,  2.6925e-04,  4.3070e-05,  ...,  1.3805e-01,
         -2.4794e-04, -1.2559e-01],
        [ 2.4708e-05,  1.9627e-05, -3.5373e-05,  ...,  1.0420e-01,
          1.0540e-02, -1.2272e-01],
        [ 3.3263e-04,  5.3075e-04, -1.4312e-04,  ...,  6.4947e-02,
          1.9557e-02, -1.2023e-01]], dtype=torch.float64)

In [13]:
V @ D

tensor([[ 0.0738,  0.1534,  0.2171,  ...,  1.3267,  1.4240,  1.4907],
        [-0.3314, -0.7402, -1.0791,  ..., -2.0938, -2.3833, -2.6647],
        [-0.0965, -0.2242, -0.3344,  ..., -0.3504, -0.4744, -0.6161],
        ...,
        [-0.2661, -0.5928, -0.8709,  ..., -1.2687, -1.5207, -1.8017],
        [-0.1132, -0.2638, -0.3924,  ...,  0.8958,  0.7705,  0.5429],
        [ 0.0675,  0.1531,  0.2184,  ..., -0.9400, -0.9562, -0.8823]],
       dtype=torch.float64)

In [14]:
V @ torch.diag(L) @ V.T

tensor([[1.3812, 1.4008, 1.3055,  ..., 0.3811, 0.3924, 0.4066],
        [1.4008, 1.4733, 1.4337,  ..., 0.3140, 0.3293, 0.3408],
        [1.3055, 1.4337, 1.4954,  ..., 0.1973, 0.2117, 0.2133],
        ...,
        [0.3811, 0.3140, 0.1973,  ..., 1.8609, 1.7919, 1.6707],
        [0.3924, 0.3293, 0.2117,  ..., 1.7919, 1.7532, 1.6681],
        [0.4066, 0.3408, 0.2133,  ..., 1.6707, 1.6681, 1.6351]],
       dtype=torch.float64)

In [15]:
V@V.T

tensor([[ 1.0000e+00, -1.3414e-16, -1.1787e-16,  ..., -1.3010e-17,
         -5.1174e-17, -3.6429e-17],
        [-1.3414e-16,  1.0000e+00, -1.9891e-16,  ..., -8.6302e-17,
         -4.9440e-17,  6.5052e-18],
        [-1.1787e-16, -1.9891e-16,  1.0000e+00,  ...,  8.8905e-17,
          1.6567e-16,  1.4051e-16],
        ...,
        [-1.5422e-17, -7.9729e-17,  9.6196e-17,  ...,  1.0000e+00,
         -2.7235e-16, -1.9255e-16],
        [-5.1324e-17, -4.2418e-17,  1.7278e-16,  ..., -2.7235e-16,
          1.0000e+00,  5.2042e-17],
        [-3.6429e-17,  6.5052e-18,  1.4051e-16,  ..., -1.9255e-16,
          5.2042e-17,  1.0000e+00]], dtype=torch.float64)

In [35]:
# Z = torch.diag(torch.pow(L, -0.5)) @ V @ D
# Z = V @ torch.diag(torch.pow(L, -0.5)) @ V.T @ D
Z = V @ torch.diag(1.0/torch.sqrt(L)) @ V.T @ D
Z

tensor([[-0.0279, -0.0678, -0.0963,  ..., -0.2493, -0.2596, -0.2605],
        [ 0.0099,  0.0386,  0.0499,  ..., -0.1142, -0.1101, -0.1629],
        [ 0.0588,  0.1401,  0.1590,  ..., -0.4102, -0.3849, -0.2761],
        ...,
        [ 0.3246,  0.5856,  0.6750,  ...,  0.2903,  0.4029,  0.6697],
        [ 0.1021,  0.2030,  0.2036,  ..., -0.0215,  0.1614,  0.3759],
        [-0.1322, -0.2947, -0.4337,  ...,  0.0045, -0.1860, -0.4266]],
       dtype=torch.float64)

In [38]:
torch.cov(Z,correction=0)

tensor([[ 9.9998e-01,  3.9401e-05,  9.2811e-05,  ..., -1.4207e-05,
          4.8166e-07,  6.8293e-06],
        [ 3.9401e-05,  9.9991e-01, -2.1784e-04,  ...,  3.3355e-05,
         -1.1268e-06, -1.6034e-05],
        [ 9.2811e-05, -2.1784e-04,  1.0005e+00,  ..., -7.5726e-06,
         -6.0532e-07,  1.6210e-06],
        ...,
        [-1.4207e-05,  3.3355e-05, -7.5726e-06,  ...,  1.0000e+00,
         -4.2633e-07,  7.6639e-07],
        [ 4.8166e-07, -1.1268e-06, -6.0532e-07,  ..., -4.2633e-07,
          1.0000e+00,  2.6083e-07],
        [ 6.8293e-06, -1.6034e-05,  1.6210e-06,  ...,  7.6639e-07,
          2.6083e-07,  1.0000e+00]], dtype=torch.float64)

In [23]:
torch.round(V@V.T, decimals=4)

tensor([[1., -0., -0.,  ..., -0., -0., -0.],
        [-0., 1., -0.,  ..., -0., -0., 0.],
        [-0., -0., 1.,  ..., 0., 0., 0.],
        ...,
        [-0., -0., 0.,  ..., 1., -0., -0.],
        [-0., -0., 0.,  ..., -0., 1., 0.],
        [-0., 0., 0.,  ..., -0., 0., 1.]], dtype=torch.float64)

In [21]:
Z = V @ torch.diag(torch.pow(L, -0.5)) @ V.T @ D
Z @ Z.T/4e4

tensor([[ 9.9998e-01,  3.9401e-05,  9.2811e-05,  ..., -1.4207e-05,
          4.8166e-07,  6.8293e-06],
        [ 3.9401e-05,  9.9991e-01, -2.1784e-04,  ...,  3.3355e-05,
         -1.1268e-06, -1.6034e-05],
        [ 9.2811e-05, -2.1784e-04,  1.0005e+00,  ..., -7.5726e-06,
         -6.0532e-07,  1.6210e-06],
        ...,
        [-1.4207e-05,  3.3355e-05, -7.5726e-06,  ...,  1.0000e+00,
         -4.2633e-07,  7.6639e-07],
        [ 4.8166e-07, -1.1268e-06, -6.0532e-07,  ..., -4.2633e-07,
          1.0000e+00,  2.6083e-07],
        [ 6.8293e-06, -1.6034e-05,  1.6210e-06,  ...,  7.6639e-07,
          2.6083e-07,  1.0000e+00]], dtype=torch.float64)

In [20]:
Z = torch.diag(torch.pow(L, -0.5)) @ V.T @ D
Z @ Z.T/4e4

tensor([[ 9.9931e-01, -4.0839e-03, -7.6688e-03,  ..., -9.1691e-10,
         -9.9822e-10,  3.0783e-10],
        [-4.0839e-03,  1.0033e+00,  7.2101e-03,  ...,  9.2202e-10,
          7.9283e-10,  5.6489e-10],
        [-7.6688e-03,  7.2101e-03,  9.9863e-01,  ..., -1.9197e-10,
         -8.5396e-10,  1.7387e-10],
        ...,
        [-9.1691e-10,  9.2202e-10, -1.9197e-10,  ...,  1.0000e+00,
         -1.0740e-16, -2.6943e-16],
        [-9.9822e-10,  7.9283e-10, -8.5396e-10,  ..., -1.0740e-16,
          1.0000e+00, -5.0833e-16],
        [ 3.0783e-10,  5.6489e-10,  1.7387e-10,  ..., -2.6462e-16,
         -5.0115e-16,  1.0000e+00]], dtype=torch.float64)